import os
from datetime import date

import markdown as md
import nh3
from deepagents import FilesystemPermission, create_deep_agent
from deepagents.backends import FilesystemBackend
from langchain_core.tools import tool
from tavily import TavilyClient

from models import model, strong_model

# Write the agent's virtual files (/research/**, /output/**) to real files
# under this module's own folder, instead of the default StateBackend which
# only keeps them in memory (inside `result`, gone once the process exits).
backend = FilesystemBackend(root_dir=os.path.dirname(os.path.abspath(__file__)))


# The distributor's top genres — known up front, no database needed.
TOP_GENRES = ["Rock", "Nova MPB", "Metal", "Alternative & Punk"]

# The model's training data has its own cutoff, unrelated to when this script
# actually runs — without this, it defaults to that cutoff year in search
# queries (e.g. "Rock news 2024"), skewing internet_search results stale.
TODAY = date.today().isoformat()

#tools
tavily_api_key = os.environ.get("TAVILY_API_KEY")
if not tavily_api_key:
    raise RuntimeError(
        "TAVILY_API_KEY is required for the Module 4.2 newsletter lab. "
        "Set it in your environment before running m4.2_run_newsletter.py."
    )

_tavily = TavilyClient(api_key=tavily_api_key)

@tool
def internet_search(query: str, max_results: int = 8) -> dict:
    """Search the web for recent news. Use this to research what's new in a
    music genre — new releases, notable artists, trends, and events."""
    return _tavily.search(query, max_results=max_results, topic="news")

@tool
def markdown_to_html(markdown_text: str, title: str = "This Week in Music") -> str:
    """Convert a Markdown newsletter into a complete, styled HTML page.
    Returns the full HTML document as a string."""
    body = md.markdown(markdown_text, extensions=["tables", "fenced_code"])
    # Good practice: the newsletter text is derived from untrusted web search,
    # so allowlist-sanitize it (strips <script>, onerror=, etc.) before it goes
    # into the page. We clean only the body; the template itself is trusted.
    body = nh3.clean(body)
    return _HTML_TEMPLATE.format(title=title, body=body)

_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  body {{ max-width: 760px; margin: 40px auto; padding: 0 20px;
          font-family: -apple-system, "Segoe UI", Roboto, sans-serif;
          line-height: 1.6; color: #1a1a1a; }}
  h1 {{ font-size: 2rem; border-bottom: 3px solid #006DDD; padding-bottom: .3em; }}
  h2 {{ color: #006DDD; margin-top: 1.6em; }}
  footer {{ margin-top: 3em; color: #777; font-size: .85rem;
            border-top: 1px solid #ddd; padding-top: 1em; }}
</style>
</head>
<body>
{body}
<footer>Generated by a Deep Agents subagent team.</footer>
</body>
</html>"""


#agents configs

# Researchers may write under /research/** and are denied writes elsewhere.
research_permissions = [
    FilesystemPermission(operations=["read", "write"], paths=["/research/**"], mode="allow"),
    FilesystemPermission(operations=["write"], paths=["/**"], mode="deny"),
]

# The editor may read the research area, but must not write into it.
editor_permissions = [
    FilesystemPermission(operations=["write"], paths=["/research/**"], mode="deny"),
]

RESEARCHER_PROMPT = f"""You are a music journalist researching one genre for an
online music distributor's weekly newsletter.

Today's date is {TODAY}. Your own training data has an earlier cutoff, so
do not assume the current year from memory - anchor to today's date instead.

You will be given a single genre and an assigned research folder to work in.

How to work:
1. Use internet_search to find recent, noteworthy developments in that genre.
   Phrase queries around the actual current timeframe (e.g. the current
   month/year from today's date above), not a year you recall from training.
   Run a few searches.
2. Save the COMPLETE, verbatim output of ALL your searches to a single file:
   write_file("/research/<genre>/sources.md", ...). Paste it exactly as the
   tool returned it - do NOT summarize or trim. This raw archive stays here so
   it never clutters the editor's context.
3. Only then, from what you found, write one tight newsletter segment.

Return ONLY the finished segment as your reply:
- A markdown section: a "## <Genre>" heading followed by ~120-180 words.
- Lively but factual newsletter tone; name specific artists and releases.
- Do NOT paste raw search results into your reply: those live in your files."""

EDITOR_PROMPT = f"""You are the editor of an online music distributor's weekly
newsletter. This week you are featuring the distributor's top genres:
{", ".join(TOP_GENRES)}.

Today's date is {TODAY}.

Your job:
1. For EACH genre, delegate to the genre-researcher subagent using the task
   tool - fire them off in parallel. Tell each one which genre to cover, which
   assigned folder to use (/research/<genre>/), and that today's date is
   {TODAY} so their research stays current. Ask for one segment.
2. Collect the four returned segments. Do NOT research genres yourself.
3. Assemble them into one Markdown newsletter: a top-level "# This Week in
   Music" title, a one-sentence intro, then the four "## <Genre>" sections.
4. Call markdown_to_html on the assembled Markdown, then write_file the
   returned HTML to /output/newsletter.html."""


genre_researcher = {
    "name": "genre-researcher",
    "description": (
        "Research one music genre and write a short newsletter segment about "
        "what's new in it. Delegate one genre per call."
    ),
    "system_prompt": RESEARCHER_PROMPT,         # its own brain - never inherited
    "tools": [internet_search],            # override - replaces the inherited set
    "model": model,                        # override - the cheaper Haiku 4.5
    "permissions": research_permissions,   # override - scoped write access
}


agent = create_deep_agent(
    model=strong_model,
    tools=[markdown_to_html],
    system_prompt=EDITOR_PROMPT,
    subagents=[genre_researcher],
    permissions=editor_permissions,
    backend=backend,
)


result = agent.invoke({"messages":[{"role":"user", "content":"Me de a newsletter dessa semana. OBS: gere a newsletter em portugeus"}]})

